name: 'Build FreeCAD'

on:
  workflow_run:
    workflows: ["trigger"]
    types: [completed]

  workflow_dispatch:

jobs:
  build:
    name: Build FreeCAD for Arch Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Build Makepkg Docker image
        continue-on-error: true
        run: docker build -t freecad-makepkg .
          
      - name: Burn Baby Burn
        continue-on-error: true
        run: docker run -e EXPORT_PKG=1 -v $PWD/freecad-linkstage3-git:/pkg freecad-makepkg

      - name: Upload pkg as artifact
        uses: actions/upload-artifact@v2
        with:
          name: freecad-linkdaily
          path: ./freecad-linkstage3-git/*.pkg*
            
      #- name: Commit & Push
      #  continue-on-error: true
      #  run: |
      #    git config user.name github-actions
      #    git config user.email github-actions@github.com
      #    git add README.md

      #    git commit -m "Build README.md

      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push


      #- name: Export FreeCAD projects
      #  continue-on-error: true
      #  run: docker run -iv $(pwd):/3d amrit3701/freecad-cli:latest make -C /3d freecad
      #
      #- name: Commit
      #  continue-on-error: true
      #  run: |
      #    git add -f */*.stl
      #    git commit -m "Build FreeCAD projects
      #    
      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push



      #- name: Commit & Push
      #  continue-on-error: true
      #  run: |
      #    git add -f */*.stl
      #    git commit -m "Build SolveSpace projects
      #    
      #    
      #    Co-authored-by: Matteo Bonora <bonora.matteo@gmail.com>"

      #    git push

