name: 'Build FreeCAD'

on:
  workflow_run:
    workflows: [trigger]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    name: Build FreeCAD for Arch Linux
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Build Makepkg Docker image
        continue-on-error: true
        run: docker build -t freecad-makepkg .
          
      - name: Burn Baby Burn
        continue-on-error: true
        run: docker run -e EXPORT_PKG=1 -v $PWD/freecad-linkstage3-git:/pkg freecad-makepkg

      - name: Upload pkg as artifact
        uses: actions/upload-artifact@v2
        with:
          name: freecad-linkdaily
          path: ./freecad-linkstage3-git/*.pkg*
            
