name: 'Build FreeCAD'

on:
  workflow_run:
    workflows: [trigger]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    name: Build FreeCAD for Arch Linux
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Build makepkg Docker image
        continue-on-error: true
        run: docker build -t freecad-makepkg .
          
      - name: Burn Baby Burn
        continue-on-error: true
        run: docker run -e EXPORT_PKG=1 -v $PWD/freecad-linkdaily-git:/pkg freecad-makepkg
      - name: Retrieve version info
        id: version
        run: |
          pkgbase="$(awk '{ if ($1 ~ /pkgbase/) {print $3} }' freecad-linkdaily-git/.SRCINFO)"
          pkgver="$(awk '{ if ($1 ~ /pkgver/) {print $3} }' freecad-linkdaily-git/.SRCINFO)"
          pkgrel="$(awk '{ if ($1 ~ /pkgrel/) {print $3} }' freecad-linkdaily-git/.SRCINFO)"
          arch="$(awk '{ if ($1 ~ /arch/) {print $3} }' freecad-linkdaily-git/.SRCINFO)"
          echo "::set-output name=pkgbase::$pkgbase"
          echo "::set-output name=pkgver::$pkgver"
          echo "::set-output name=pkgrel::$pkgrel"
          echo "::set-output name=arch::$arch"

          ls -al ./freecad-linkdaily-git
          echo "::set-output name=filename::$(ls ./freecad-linkdaily-git/*.pkg.tar* | tail -n1)"
          #echo "::set-output name=filename::freecad-linkdaily-git-$pkgver-$pkgrel-$arch.pkg.tar"
          
          #- name: Upload pkg as artifact
          #  uses: actions/upload-artifact@v2
          #  with:
          #    name: freecad-linkdaily
          #    path: ./freecad-linkdaily-git/*.pkg.tar*

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: falsze
          release_name: ${{ steps.version.outputs.pkgver }}
          tag_name: ${{ github.ref }}
          body: |
            # FreeCAD LinkDaily
            version ${{ steps.version.outputs.pkgver }}

      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./freecad-linkdaily-git/${{ steps.version.outputs.filename }}
          asset_name: ${{ steps.version.outputs.filename }}
          asset_content_type: application/x-tar

      - name: Upload SRCINFO to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./freecad-linkdaily-git/.SRCINFO
          asset_name: .SRCINFO
          asset_content_type: text/plain

